"""Initial migration

Revision ID: 0b36453991e8
Revises: 
Create Date: 2025-05-20 21:18:11.091429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b36453991e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coord',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Coord_id'), 'Coord', ['id'], unique=False)
    op.create_table('Level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('winter', sa.String(length=2), nullable=True),
    sa.Column('summer', sa.String(length=2), nullable=True),
    sa.Column('autumn', sa.String(length=2), nullable=True),
    sa.Column('spring', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Level_id'), 'Level', ['id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('patronymic', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_table('Mountain_Pass',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beauty_title', sa.String(length=250), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('other_titles', sa.String(length=250), nullable=False),
    sa.Column('connect', sa.Text(), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coord_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'pending', 'accepted', 'rejected', name='statusenum'), nullable=False),
    sa.ForeignKeyConstraint(['coord_id'], ['Coord.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['Level.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Mountain_Pass_id'), 'Mountain_Pass', ['id'], unique=False)
    op.create_table('Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('pass_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pass_id'], ['Mountain_Pass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Image_id'), 'Image', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Image_id'), table_name='Image')
    op.drop_table('Image')
    op.drop_index(op.f('ix_Mountain_Pass_id'), table_name='Mountain_Pass')
    op.drop_table('Mountain_Pass')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Level_id'), table_name='Level')
    op.drop_table('Level')
    op.drop_index(op.f('ix_Coord_id'), table_name='Coord')
    op.drop_table('Coord')
    # ### end Alembic commands ###
